Presentation
oberien/pundoc pull request #97
Opened 2019-08-18 09:27 UTC by oberien

Largely rewrite beamer from #15.

2019-08-18 15:00 UTC, 197g requested changes
Much nicer with stateful access to the backend. 

I'm not completely sold on the style for headings but the previous PR was not perfect as well. In all other markdown editors the frame delimiters, the rulers (`---`), appear at a smaller structural level than the boxes and are more easily overlooked.

2019-08-18 15:00 UTC, 197g commented on src/backend/latex/document/beamer.rs
> +                    writeln!(out, "\\Huge\\centering \\insertsection")?;
If I don't want to use a full page sized frame for sections in a presentation (i.e. too short) and don't use *any* section headers then this creates a completely empty page.

2019-08-18 15:00 UTC, 197g commented on src/util.rs
> +    join_chars: &'a [u8],
Based on usage and **`chars`** I would have expected a `&'a str`.

2019-08-18 15:00 UTC, 197g commented on src/backend/latex/document/beamer.rs
> +        writeln!(out, "\\usetheme{{Madrid}}")?;
Can we include a configuration option for the theme/color? I don't like blue and the solid color bars top and bottom of Madrid :smile:

2019-08-20 21:33 UTC, oberien commented
I added a `sectionframes` and `beamertheme` config option.

As said in https://github.com/oberien/heradoc/pull/15#issuecomment-519085285 I followed the default way pandoc handles it.

2019-08-21 14:24 UTC, 197g approved these changes

2019-08-21 14:46 UTC, merged